name:                my-xmonad
version:             0.1.0.0
license:             BSD3
author:              "Marcin Szleper <marcin.szleper@gmail.com>"
maintainer:          "Marcin Szleper <marcin.szleper@gmail.com>"
copyright:           "2020 Marcin Szleper"

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.15
- xmonad-contrib >= 0.15
- containers
- utf8-string
- X11
- bytestring

library:
  source-dirs: lib

executables:
  my-xmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
